#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define TAPPING_TERM 165

#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD

#define SPLIT_USB_DETECT
#define SPLIT_WPM_ENABLE

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_TIME_TO_MAX 60

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 30
#define MOUSEKEY_WHEEL_MAX_SPEED 3
#define MOUSEKEY_WHEEL_TIME_TO_MAX 60
